[build]
  publish = "frontend/dist/"
  command = "make all"
  functions = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/darrenparkinson/rolling-days-off"

[[redirects]]
  from = "/api/v1/daysoff"
  to = "/.netlify/functions/daysoff"
  query = {startDate = ":startDate",endDate = ":endDate",dayOff = ":dayOff"}

